/*******************************************************************************
* FILE NAME: FastCanvas.h                                                      *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     FastCanvas- A high-performance drawing canvas                            *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_FastCanvas
#define WND_FastCanvas  VBBASEWINDOWID
#endif

#define WNDOFFSET_FastCanvas_Canvas  0
#define WND_FastCanvas_Canvas  WND_FastCanvas


