/*******************************************************************************
* FILE NAME: GraphicFileInfo.cpp                                               *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     GraphicFileInfo- Graphic File Information                                *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _GRAPHICFILEINFO_
#include "GraphicFileInfo.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (GraphicFileInfo::readyId)
const INotificationId GraphicFileInfo::readyId = "GraphicFileInfo::readyId";
//------------------------------------------------------------------------------
// GraphicFileInfo :: GraphicFileInfo
//------------------------------------------------------------------------------
#pragma export (GraphicFileInfo::GraphicFileInfo())
GraphicFileInfo::GraphicFileInfo()
{

}     //end constructor


//------------------------------------------------------------------------------
// GraphicFileInfo :: ~GraphicFileInfo
//------------------------------------------------------------------------------
#pragma export (GraphicFileInfo::~GraphicFileInfo())
GraphicFileInfo::~GraphicFileInfo()
{

}

//------------------------------------------------------------------------------
// GraphicFileInfo :: initializePart
//------------------------------------------------------------------------------
#pragma export (GraphicFileInfo::initializePart())
GraphicFileInfo & GraphicFileInfo::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// GraphicFileInfo :: makeConnections
//------------------------------------------------------------------------------
#pragma export (GraphicFileInfo::makeConnections())
Boolean GraphicFileInfo::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "GraphicFileInfo.cpv"
