/*******************************************************************************
* FILE NAME: GraphicFileInfo.hpp                                               *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     GraphicFileInfo- Graphic File Information                                *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _GRAPHICFILEINFO_
#define _GRAPHICFILEINFO_  

class GraphicFileInfo;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#include "fstream.h"

#include "stdlib.h"

#include "GraphicFileInfo.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for GraphicFileInfo
//*****************************************************************************
class GraphicFileInfo : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   GraphicFileInfo();

   virtual  ~GraphicFileInfo();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual GraphicFileInfo & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   virtual Boolean makeConnections();

private:

#include "GraphicFileInfo.hpv"
};   //GraphicFileInfo


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
