/*******************************************************************************
* FILE NAME: ImageHandler.cpp                                                  *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     ImageHandler- Image Handler                                              *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _IMAGEHANDLER_
#include "ImageHandler.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (ImageHandler::readyId)
const INotificationId ImageHandler::readyId = "ImageHandler::readyId";
//------------------------------------------------------------------------------
// ImageHandler :: ImageHandler
//------------------------------------------------------------------------------
#pragma export (ImageHandler::ImageHandler())
ImageHandler::ImageHandler()
{

}     //end constructor


//------------------------------------------------------------------------------
// ImageHandler :: ~ImageHandler
//------------------------------------------------------------------------------
#pragma export (ImageHandler::~ImageHandler())
ImageHandler::~ImageHandler()
{

}

//------------------------------------------------------------------------------
// ImageHandler :: initializePart
//------------------------------------------------------------------------------
#pragma export (ImageHandler::initializePart())
ImageHandler & ImageHandler::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// ImageHandler :: makeConnections
//------------------------------------------------------------------------------
#pragma export (ImageHandler::makeConnections())
Boolean ImageHandler::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "ImageHandler.cpv"
