/*******************************************************************************
* FILE NAME: InterfaceEnabler.cpp                                              *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     InterfaceEnabler- Enables interface components when sprite is ready      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _INTERFACEENABLER_
#include "InterfaceEnabler.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (InterfaceEnabler::readyId)
const INotificationId InterfaceEnabler::readyId = "InterfaceEnabler::readyId";

//------------------------------------------------------------------------------
// InterfaceEnabler :: InterfaceEnabler
//------------------------------------------------------------------------------
#pragma export (InterfaceEnabler::InterfaceEnabler())
InterfaceEnabler::InterfaceEnabler()
{

}     //end constructor


//------------------------------------------------------------------------------
// InterfaceEnabler :: ~InterfaceEnabler
//------------------------------------------------------------------------------
#pragma export (InterfaceEnabler::~InterfaceEnabler())
InterfaceEnabler::~InterfaceEnabler()
{

}

//------------------------------------------------------------------------------
// InterfaceEnabler :: initializePart
//------------------------------------------------------------------------------
#pragma export (InterfaceEnabler::initializePart())
InterfaceEnabler & InterfaceEnabler::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// InterfaceEnabler :: makeConnections
//------------------------------------------------------------------------------
#pragma export (InterfaceEnabler::makeConnections())
Boolean InterfaceEnabler::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "InterfaceEnabler.cpv"
