/*******************************************************************************
* FILE NAME: InterfaceEnabler.h                                                *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     InterfaceEnabler- Enables interface components when sprite is ready      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_InterfaceEnabler
#define WND_InterfaceEnabler  VBBASEWINDOWID
#endif


