/*******************************************************************************
* FILE NAME: PcxLoader.hpp                                                     *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     PcxLoader- Loads PCX files                                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _PCXLOADER_
#define _PCXLOADER_  

class PcxLoader;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#include "fstream.h"

#include "iostream.h"

#include "assert.h"

#include "PcxLoader.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for PcxLoader
//*****************************************************************************
class PcxLoader : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   PcxLoader();

   virtual  ~PcxLoader();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual PcxLoader & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   virtual Boolean makeConnections();

private:

#include "PcxLoader.hpv"
};   //PcxLoader


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
