/*******************************************************************************
* FILE NAME: SpriteDropHandler.hpp                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     SpriteDropHandler- Handle dropping files into demo                       *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _SPRITEDROPHANDLER_
#define _SPRITEDROPHANDLER_  

class SpriteDropHandler;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#include "idmhndlr.hpp"

#include "idmtgtrn.hpp"

#include "idmtgth.hpp"

#include "idmprov.hpp"

#include "idmevent.hpp"

#include "sprite.hpp"

#include "spritedetails.hpp"

#include "SpriteDropHandler.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for SpriteDropHandler
//*****************************************************************************
class SpriteDropHandler : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   SpriteDropHandler();

   virtual  ~SpriteDropHandler();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual SpriteDropHandler & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   virtual Boolean makeConnections();

private:

#include "SpriteDropHandler.hpv"
};   //SpriteDropHandler


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
