/*******************************************************************************
* FILE NAME: Sprite.cpp                                                        *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     Sprite- Sprite                                                           *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _SPRITE_
#include "Sprite.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (Sprite::readyId)
const INotificationId Sprite::readyId = "Sprite::readyId";
//------------------------------------------------------------------------------
// Sprite :: Sprite
//------------------------------------------------------------------------------
#pragma export (Sprite::Sprite())
Sprite::Sprite()
{

}     //end constructor


//------------------------------------------------------------------------------
// Sprite :: ~Sprite
//------------------------------------------------------------------------------
#pragma export (Sprite::~Sprite())
Sprite::~Sprite()
{

}

//------------------------------------------------------------------------------
// Sprite :: initializePart
//------------------------------------------------------------------------------
#pragma export (Sprite::initializePart())
Sprite & Sprite::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// Sprite :: makeConnections
//------------------------------------------------------------------------------
#pragma export (Sprite::makeConnections())
Boolean Sprite::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "Sprite.cpv"
