/*******************************************************************************
* FILE NAME: SpriteCommander.h                                                 *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     SpriteCommander- Passes commands to the selected sprite                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_SpriteCommander
#define WND_SpriteCommander  VBBASEWINDOWID
#endif


