/*******************************************************************************
* FILE NAME: SpriteDemo.hpp                                                    *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     SpriteDemo                                                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _SPRITEDEMO_
#define _SPRITEDEMO_  

class SpriteDemo;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _IACCEL_
#include <iaccel.hpp>
#endif

class IMenuBar;
class IMultiCellCanvas;
class SpriteDetails;
class FastCanvas;
class IInfoArea;
class IVBFileDialog;
#ifndef _SPRITE_
#include "Sprite.hpp"
#endif

#ifndef _IVSEQ_H_
#include <ivseq.h>
#endif

class Sprite;
#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

class SpriteCommander;
class SpriteDropHandler;
#ifndef _IVBVCLS_
#include <ivbvcls.h>
#endif

class IString;
class InterfaceEnabler;
class IVBFlyText;
class IMessageBox;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

#include "os2.h"

class SpriteDemoConn6;
class SpriteDemoConn60;
class SpriteDemoConn16;
class SpriteDemoConn62;
class SpriteDemoConn71;
class SpriteDemoConn77;
class SpriteDemoConn17;
class SpriteDemoConn20;
class SpriteDemoConn33;
class SpriteDemoConn25;
class SpriteDemoConn26;
class SpriteDemoConn37;
class SpriteDemoConn38;
class SpriteDemoConn49;
class SpriteDemoConn30;
class SpriteDemoConn41;
class SpriteDemoConn29;
class SpriteDemoConn50;
class SpriteDemoConn61;
class SpriteDemoConn48;
class SpriteDemoConn59;
class SpriteDemoConn70;
class SpriteDemoConn91;
class SpriteDemoConn74;
class SpriteDemoConn45;
class SpriteDemoConn55;
class SpriteDemoConn67;
class SpriteDemoConn78;
class SpriteDemoConn87;
class SpriteDemoConn98;
class SpriteDemoConn80;
class SpriteDemoConn51;
class SpriteDemoConn52;
class SpriteDemoConn43;
class SpriteDemoConn64;
class SpriteDemoConn65;
class SpriteDemoConn47;
class SpriteDemoConn57;
#include "SpriteDemo.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for SpriteDemoSpriteFactoryFactory
//*****************************************************************************
class SpriteDemoSpriteFactoryFactory : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   SpriteDemoSpriteFactoryFactory();

   virtual  ~SpriteDemoSpriteFactoryFactory();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   Sprite * create();
   SpriteDemoSpriteFactoryFactory & setFastCanvas1(FastCanvas * aSelf) {iFastCanvas1 = aSelf; return *this;};
   SpriteDemoSpriteFactoryFactory & setnewFilename(IVBVariableClass<IString> * aSelf) {inewFilename = aSelf; return *this;};

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId newObjectCreatedId;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   FastCanvas * iFastCanvas1;
   IVBVariableClass<IString> * inewFilename;


};   //SpriteDemoSpriteFactoryFactory


//*****************************************************************************
// Class definition for SpriteDemo
//*****************************************************************************
class SpriteDemo : public IFrameWindow, public IObserver {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   SpriteDemo(
      unsigned long id = WND_SpriteDemo,
      IWindow * parent = IWindow::desktopWindow(),
      IWindow * owner = 0,
      const IRectangle & rect = defaultFramingSpec(),
      const IFrameWindow::Style & style = defaultStyle(),
      const char * title = defaultTitle());

   virtual  ~SpriteDemo();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual SpriteDemo & initializePart();
   SpriteDemo * getFrameWindow() { return this; };
   IVSequence< Sprite* > *  getSpriteCollection() const { return iSpriteCollection; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();
   virtual IObserver & dispatchNotificationEvent(const INotificationEvent & anEvent);

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IMenuBar * iFrameWindowMenu;
   IAccelerator * iFrameWindowAccelTable;
   IMultiCellCanvas * iMultiCellCanvas1;
   SpriteDetails * iSpriteDetails;
   FastCanvas * iFastCanvas1;
   IInfoArea * iInfoArea1;
   IVBFileDialog * iOpenSprite;
   IVSequence< Sprite* > * iSpriteCollection;
   SpriteDemoSpriteFactoryFactory * iSpriteFactory;
   SpriteCommander * iSpriteCommander;
   SpriteDropHandler * iSpriteDropHandler;
   IVBVariableClass<IString> * inewFilename;
   InterfaceEnabler * iInterfaceEnabler;
   IVBFlyText * iVBFlyText1;
   IMessageBox * iMessageBox1;
   SpriteDemoConn6 * conn6;
   SpriteDemoConn60 * conn60;
   SpriteDemoConn16 * conn16;
   SpriteDemoConn62 * conn62;
   SpriteDemoConn71 * conn71;
   SpriteDemoConn77 * conn77;
   SpriteDemoConn17 * conn17;
   SpriteDemoConn20 * conn20;
   SpriteDemoConn33 * conn33;
   SpriteDemoConn25 * conn25;
   SpriteDemoConn26 * conn26;
   SpriteDemoConn37 * conn37;
   SpriteDemoConn38 * conn38;
   SpriteDemoConn49 * conn49;
   SpriteDemoConn30 * conn30;
   SpriteDemoConn41 * conn41;
   SpriteDemoConn29 * conn29;
   SpriteDemoConn50 * conn50;
   SpriteDemoConn61 * conn61;
   SpriteDemoConn48 * conn48;
   SpriteDemoConn59 * conn59;
   SpriteDemoConn70 * conn70;
   SpriteDemoConn91 * conn91;
   SpriteDemoConn74 * conn74;
   SpriteDemoConn45 * conn45;
   SpriteDemoConn55 * conn55;
   SpriteDemoConn67 * conn67;
   SpriteDemoConn78 * conn78;
   SpriteDemoConn87 * conn87;
   SpriteDemoConn98 * conn98;
   SpriteDemoConn80 * conn80;
   SpriteDemoConn51 * conn51;
   SpriteDemoConn52 * conn52;
   SpriteDemoConn43 * conn43;
   SpriteDemoConn64 * conn64;
   SpriteDemoConn65 * conn65;
   SpriteDemoConn47 * conn47;
   SpriteDemoConn57 * conn57;


#include "SpriteDemo.hpv"
};   //SpriteDemo


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
