/*******************************************************************************
* FILE NAME: SpriteDetails.h                                                   *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     SpriteDetails- Details view of sprite info                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_SpriteDetails
#define WND_SpriteDetails  VBBASEWINDOWID
#endif

#define WNDOFFSET_SpriteDetails_VBContainerControl  0
#define WND_SpriteDetails_VBContainerControl  WND_SpriteDetails






