/*******************************************************************************
* FILE NAME: SpriteDetails.hpp                                                 *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     SpriteDetails- Details view of sprite info                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _SPRITEDETAILS_
#define _SPRITEDETAILS_  

class SpriteDetails;

#ifndef _SPRITE_
#include "Sprite.hpp"
#endif

#ifndef _IVSEQ_H_
#include <ivseq.h>
#endif

#ifndef _IVBCNR_
#include <ivbcnr.h>
#endif

#define INCL_WINSTDCNR
#include <os2.h>

class IContainerColumn;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ICNRCTL_
#include <icnrctl.hpp>
#endif

#include "itrace.hpp"

#include "SpriteDropHandler.hpp"

#include "SpriteDetails.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for SpriteDetailsVBContainerControlCnrObj
//*****************************************************************************
class SpriteDetailsVBContainerControlCnrObj : public IVBContainerObject {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   SpriteDetailsVBContainerControlCnrObj(Sprite& anObject);
   SpriteDetailsVBContainerControlCnrObj(SpriteDetailsVBContainerControlCnrObj& anObject);

   virtual  ~SpriteDetailsVBContainerControlCnrObj();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   IVBContainerObject & refreshFromObject();
   IVBContainerObject & updateToObject();
   SpriteDetailsVBContainerControlCnrObj& operator=(const SpriteDetailsVBContainerControlCnrObj& anObject);
   Sprite* realObject() { return &pRealObject; }
;

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   IString inumFramesAsText;
   IString iactiveFrameAsText;
   IString ipositionAsText;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   Sprite & pRealObject;


};   //SpriteDetailsVBContainerControlCnrObj


//*****************************************************************************
// Class definition for SpriteDetails
//*****************************************************************************
class SpriteDetails : public IVBContainerControl< Sprite*, IVSequence<Sprite*>, SpriteDetailsVBContainerControlCnrObj > {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   SpriteDetails(
      unsigned long id = WND_SpriteDetails,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IContainerControl::Style& style = defaultStyle(),
      const IContainerControl::Attribute& attribute = IContainerControl::defaultAttribute ( ));

   virtual  ~SpriteDetails();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IContainerControl::Style defaultStyle();
   virtual SpriteDetails & initializePart();
   SpriteDetails * getVBContainerControl() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IContainerColumn * iContainerColumn1;
   IContainerColumn * iContainerColumn2;
   IContainerColumn * iContainerColumn3;
   IContainerColumn * iContainerColumn4;


#include "SpriteDetails.hpv"
};   //SpriteDetails


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
