/*******************************************************************************
* FILE NAME: SpriteDemo.h                                                      *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     SpriteDemo                                                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_SpriteDemo
#define WND_SpriteDemo  VBBASEWINDOWID
#endif

#define WNDOFFSET_SpriteDemo_FrameWindow  0
#define WND_SpriteDemo_FrameWindow  WND_SpriteDemo
#define ACCEL_SpriteDemo_FrameWindow  WND_SpriteDemo_FrameWindow

#define WND_SpriteDemo_MultiCellCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_SpriteDemo_SpriteDetails  1
#define WND_SpriteDemo_SpriteDetails  WND_SpriteDemo + WNDOFFSET_SpriteDemo_SpriteDetails
#define STRRC_SpriteDemo_SpriteDetails_avlFlyOverShortText  WND_SpriteDemo_SpriteDetails + VBSHORTFLYTEXTOFFSET
#define STRRC_SpriteDemo_SpriteDetails_avlFlyOverLongText  WND_SpriteDemo_SpriteDetails + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_SpriteDemo_FastCanvas1  2
#define WND_SpriteDemo_FastCanvas1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_FastCanvas1
#define STRRC_SpriteDemo_FastCanvas1_avlFlyOverShortText  WND_SpriteDemo_FastCanvas1 + VBSHORTFLYTEXTOFFSET
#define STRRC_SpriteDemo_FastCanvas1_avlFlyOverLongText  WND_SpriteDemo_FastCanvas1 + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_SpriteDemo_InfoArea1  3
#define WND_SpriteDemo_InfoArea1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_InfoArea1

#define WNDOFFSET_SpriteDemo_Menu1  4
#define WND_SpriteDemo_Menu1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_Menu1

#define WNDOFFSET_SpriteDemo_FileMenuCascade  5
#define WND_SpriteDemo_FileMenuCascade  WND_SpriteDemo + WNDOFFSET_SpriteDemo_FileMenuCascade
#define STRRC_SpriteDemo_FileMenuCascade_avlInfoAreaText  WND_SpriteDemo_FileMenuCascade + VBINFOAREATEXTOFFSET

#define WNDOFFSET_SpriteDemo_FrameMenuCascade  6
#define WND_SpriteDemo_FrameMenuCascade  WND_SpriteDemo + WNDOFFSET_SpriteDemo_FrameMenuCascade
#define STRRC_SpriteDemo_FrameMenuCascade_avlInfoAreaText  WND_SpriteDemo_FrameMenuCascade + VBINFOAREATEXTOFFSET

#define WNDOFFSET_SpriteDemo_MoveMenuCascade  7
#define WND_SpriteDemo_MoveMenuCascade  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MoveMenuCascade
#define STRRC_SpriteDemo_MoveMenuCascade_avlInfoAreaText  WND_SpriteDemo_MoveMenuCascade + VBINFOAREATEXTOFFSET

#define WNDOFFSET_SpriteDemo_fileMenu  8
#define WND_SpriteDemo_fileMenu  WND_SpriteDemo + WNDOFFSET_SpriteDemo_fileMenu

#define WNDOFFSET_SpriteDemo_openMenuItem  9
#define WND_SpriteDemo_openMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_openMenuItem

#define WNDOFFSET_SpriteDemo_MenuSeparator4  10
#define WND_SpriteDemo_MenuSeparator4  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MenuSeparator4

#define WNDOFFSET_SpriteDemo_exitMenuItem  11
#define WND_SpriteDemo_exitMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_exitMenuItem

#define WNDOFFSET_SpriteDemo_MoveMenu  12
#define WND_SpriteDemo_MoveMenu  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MoveMenu

#define WNDOFFSET_SpriteDemo_MenuSeparator1  13
#define WND_SpriteDemo_MenuSeparator1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MenuSeparator1

#define WNDOFFSET_SpriteDemo_moveRight  14
#define WND_SpriteDemo_moveRight  WND_SpriteDemo + WNDOFFSET_SpriteDemo_moveRight

#define WNDOFFSET_SpriteDemo_MenuItem3  15
#define WND_SpriteDemo_MenuItem3  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MenuItem3

#define WNDOFFSET_SpriteDemo_upMenuItem  16
#define WND_SpriteDemo_upMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_upMenuItem

#define WNDOFFSET_SpriteDemo_downMenuItem  17
#define WND_SpriteDemo_downMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_downMenuItem

#define WNDOFFSET_SpriteDemo_MenuSeparator2  18
#define WND_SpriteDemo_MenuSeparator2  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MenuSeparator2

#define WNDOFFSET_SpriteDemo_MenuItem1  19
#define WND_SpriteDemo_MenuItem1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MenuItem1

#define WNDOFFSET_SpriteDemo_MenuItem11  20
#define WND_SpriteDemo_MenuItem11  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MenuItem11

#define WNDOFFSET_SpriteDemo_FastUpMenuItem  21
#define WND_SpriteDemo_FastUpMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_FastUpMenuItem

#define WNDOFFSET_SpriteDemo_FastDownMenuItem  22
#define WND_SpriteDemo_FastDownMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_FastDownMenuItem

#define WNDOFFSET_SpriteDemo_OpenSprite  23
#define WND_SpriteDemo_OpenSprite  WND_SpriteDemo + WNDOFFSET_SpriteDemo_OpenSprite


#define WNDOFFSET_SpriteDemo_SpriteFactory  24
#define WND_SpriteDemo_SpriteFactory  WND_SpriteDemo + WNDOFFSET_SpriteDemo_SpriteFactory


#define WNDOFFSET_SpriteDemo_FrameMenu  24
#define WND_SpriteDemo_FrameMenu  WND_SpriteDemo + WNDOFFSET_SpriteDemo_FrameMenu

#define WNDOFFSET_SpriteDemo_previousFrameMenuItem  25
#define WND_SpriteDemo_previousFrameMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_previousFrameMenuItem

#define WNDOFFSET_SpriteDemo_nextFrameMenuItem  26
#define WND_SpriteDemo_nextFrameMenuItem  WND_SpriteDemo + WNDOFFSET_SpriteDemo_nextFrameMenuItem




#define WNDOFFSET_SpriteDemo_VBFlyText1  27
#define WND_SpriteDemo_VBFlyText1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_VBFlyText1

#define WNDOFFSET_SpriteDemo_MessageBox1  28
#define WND_SpriteDemo_MessageBox1  WND_SpriteDemo + WNDOFFSET_SpriteDemo_MessageBox1


